$FileMI = GUICtrlCreateMenu("File")
	$MenuItem5 = GUICtrlCreateMenuItem("Open Project", $FileMI)
	$MenuItem6 = GUICtrlCreateMenuItem("Switch Project", $FileMI)
	$MenuItem7 = GUICtrlCreateMenuItem("Close", $FileMI)
	GUICtrlCreateMenuItem("", $FileMI)
	$MenuItem8 = GUICtrlCreateMenuItem("Exit", $FileMI)
$OptionsMI = GUICtrlCreateMenu("Options")
	$MenuItem9 = GUICtrlCreateMenuItem("Always On Top", $OptionsMI)
	$MenuItem10 = GUICtrlCreateMenuItem("Rules", $OptionsMI)
	$MenuItem11 = GUICtrlCreateMenuItem("Settings", $OptionsMI)
$AdministratorMI = GUICtrlCreateMenu("Administrator")
	$MenuItem12 = GUICtrlCreateMenuItem("New Project", $AdministratorMI)
	$MenuItem13 = GUICtrlCreateMenuItem("Import Project", $AdministratorMI)
	$MenuItem14 = GUICtrlCreateMenuItem("Export Project", $AdministratorMI)
	$MenuItem15 = GUICtrlCreateMenuItem("Project Settings", $AdministratorMI)
$HelpMI = GUICtrlCreateMenu("Help")
	$MenuItem16 = GUICtrlCreateMenuItem("[Project] Site", $HelpMI)
	$MenuItem17 = GUICtrlCreateMenuItem("Using WMS", $HelpMI)
	$MenuItem18 = GUICtrlCreateMenuItem("Check for Updates", $HelpMI)
	GUICtrlCreateMenuItem("", $HelpMI)
	$MenuItem19 = GUICtrlCreateMenuItem("About", $HelpMI)
